version: '3'
services:
  postgres:
    image: postgres:15
    container_name: postgres
    hostname: postgres
    ports:
      - '5555:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=library
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    restart: always
    networks:
      - library-network

volumes:
  postgresql_data:
    driver: local

networks:
  library-network:
    driver: bridge