version: '3'
services:
  postgres:
    image: postgres:15
    container_name: postgres
    hostname: postgres
    ports:
      - '5555:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=library
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    restart: always
    networks:
      - library-network
  redis:
    image: redis:latest
    container_name: redis
    hostname: redis
    ports:
      - '6379:6379'
    environment:
      - REDIS_PORT=6379
      - REDIS_PASSWORD=password
      - REDIS_DATABASES=1
    volumes:
      - redis_data:/data
    restart: always
    networks:
      - library-network

volumes:
  postgresql_data:
    driver: local
  redis_data:
    driver: local

networks:
  library-network:
    driver: bridge