server:
  port: ${SERVICE_PORT:8082}
spring:
  name: ${SERVICE_NAME:recommendation-service}
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${POSTGRES_PATH:jdbc:postgresql://localhost:5555/library}
    username: ${POSTGRES_USERNAME:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
  flyway:
    default-schema: recommendation-service
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        default_schema: ${spring.flyway.default-schema}
recommendation-service:
  notification-job:
    initial-delay: 10000
    fixed-delay: 10000
catalog-service:
  graphql:
    url: ${CATALOG_SERVICE_GRAPHQL_URL:http://localhost:8081/graphql}